In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4) #creates a tensor 0 dimensional tensor

In [4]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([1.0,2,-4])
print(tensor_one_d)

tf.Tensor([ 1.  2. -4.], shape=(3,), dtype=float32)


In [6]:
tensor_two_d  = tf.constant([
    [2,5,-1],
    [2,4,1],
    [3,123,5],
    [3,8,9]
])

In [7]:
print(tensor_two_d)

tf.Tensor(
[[  2   5  -1]
 [  2   4   1]
 [  3 123   5]
 [  3   8   9]], shape=(4, 3), dtype=int32)


In [8]:
tensor_three_d = tf.constant([
    [
        [1,4,3],
        [1,5,454],
        [34,565,424],
        [123,453,67]
    ],
    [
        [1,4,3],
        [1,5,454],
        [34,565,424],
        [123,453,67]
    ]
    
])

print(tensor_three_d)

tf.Tensor(
[[[  1   4   3]
  [  1   5 454]
  [ 34 565 424]
  [123 453  67]]

 [[  1   4   3]
  [  1   5 454]
  [ 34 565 424]
  [123 453  67]]], shape=(2, 4, 3), dtype=int32)


In [9]:
print(tensor_three_d.shape)

(2, 4, 3)


In [10]:
print(tensor_three_d.ndim) # 3 d tensor

3


In [11]:
tensor_four_d = tf.constant([
    [
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,3,4,65],
            [34,5,4,657,324]
        ],
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,3,4,65],
            [34,54,65,7,324]
        ],
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [2,3,6,34,65],
            [34,54,6,57,324]
        ],
    ],
     [
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,3,4,65],
            [34,54,657,3,24]
        ],
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,34,6,5],
            [34,54,657,3,24]
        ],
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,34,65,4],
            [34,54,657,2,324]
        ]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6   3   4  65]
   [ 34   5   4 657 324]]

  [[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6   3   4  65]
   [ 34  54  65   7 324]]

  [[  1   2   3   4   5]
   [  4   2   7   2   6]
   [  2   3   6  34  65]
   [ 34  54   6  57 324]]]


 [[[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6   3   4  65]
   [ 34  54 657   3  24]]

  [[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6  34   6   5]
   [ 34  54 657   3  24]]

  [[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6  34  65   4]
   [ 34  54 657   2 324]]]], shape=(2, 3, 4, 5), dtype=int32)


In [12]:
tensor_one_d_32 = tf.constant([23,4,5,1], dtype=tf.float32) #pecision value is 32, if it is float16 then less memory is required to store it

In [13]:
print(tensor_one_d_32)

tf.Tensor([23.  4.  5.  1.], shape=(4,), dtype=float32)


In [14]:
casted_tensor_one_d = tf.cast(tensor_one_d , dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [15]:
tensor_bool = tf.constant([True, True, False, True])
print(tensor_bool)

tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


In [16]:
cast_tensor_bool = tf.cast(tensor_bool , dtype=tf.int16)
print(cast_tensor_bool)

tf.Tensor([1 1 0 1], shape=(4,), dtype=int16)


In [17]:
tensor_string = tf.constant("Hello world")
print(tensor_string)

tf.Tensor(b'Hello world', shape=(), dtype=string)


In [18]:
#creating a four dimensional tensor of type string with dimension 2*2*3*1

tensor_string_four_d = tf.constant([
    [
        [
           ["hello World"],
           ["hello World"],
           ["hello World"] 
        ],
        [
            ["hello World"],
            ["hello World"],
            ["hello World"]
        ]
    ],
    [
         [
            ["hello World"],
            ["hello World"],
            ["hello World"]
         ],
         [
            ["hello World"],
            ["hello World"],
            ["hello World"]
         ]
    ]
])
print(tensor_string_four_d)

tf.Tensor(
[[[[b'hello World']
   [b'hello World']
   [b'hello World']]

  [[b'hello World']
   [b'hello World']
   [b'hello World']]]


 [[[b'hello World']
   [b'hello World']
   [b'hello World']]

  [[b'hello World']
   [b'hello World']
   [b'hello World']]]], shape=(2, 2, 3, 1), dtype=string)


In [19]:
import numpy as np 


In [20]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [21]:
print(np_array.shape)

(3,)


In [22]:
#converting the numpy array into tensor
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [23]:
#identity matrix

eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None, #when we define the number of columns as n then the number of columns automatically takes in the value of n
    batch_shape=[2,2], #batch size determines the dimensions of the matrices if batch_shape = [2,] that is we want 2 5*5 identity matrices
    dtype=tf.dtypes.float64,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 2, 5, 5), dtype=float64)


In [24]:
#the fill method creates a tensor filled with a scalar value
tensor_nine = tf.fill([2,3,5,5],9)
print(tensor_nine)

tf.Tensor(
[[[[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]

  [[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]

  [[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]]


 [[[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]

  [[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]

  [[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]]], shape=(2, 3, 5, 5), dtype=int32)


In [25]:
#tf.ones() mehod creates a tensor with all elements set to one

tensor_one = tf.ones(
    shape=[2,2],
    dtype=tf.float16,
    name=None
)

print(tensor_one)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float16)


In [26]:
#the method tf.ones_like() : - creates a tensor of all ones that has the same shape as the input

#it will create the same array (same dimension) as the input array that is passed to it with all its values set to 1

ones_like_tensor = tf.ones_like(
    tensor_nine , dtype=tf.int16 , name=None
)

print(ones_like_tensor)



tf.Tensor(
[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]], shape=(2, 3, 5, 5), dtype=int16)


In [27]:
#tf.zeros method creates a tensor with all elements set to zero

zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.float32,
    name=None
)

print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [28]:
print(tf.shape(tensor_three_d)) #prints the shape of the tensor tensor_three_d as a list

tf.Tensor([2 4 3], shape=(3,), dtype=int32)


In [29]:
#the rank method returns the rank of a tensor

rank_two_d_tensor = tf.rank(
    tensor_two_d , name=None
)

print(rank_two_d_tensor)

tf.Tensor(2, shape=(), dtype=int32)


In [30]:
#the size method returns the size of a tensor

size_of_three_d_tensor = tf.size(
    tensor_three_d,
    out_type=tf.dtypes.int16,
    name=None
)
print(tensor_three_d.shape)
print(size_of_three_d_tensor)

(2, 4, 3)
tf.Tensor(24, shape=(), dtype=int16)


In [31]:
random_tensor = tf.random.normal(
    [3,2],
    mean=2.0,
    stddev=1.9,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)



tf.Tensor(
[[ 0.08374226 -0.48720312]
 [ 3.8012617   4.6803055 ]
 [ 0.33665943 -2.0321107 ]], shape=(3, 2), dtype=float32)


In [34]:
#generating random normals from uniform distribution

#tf.random.uniform : outputs random values from a uniform distribution

uniform_tensor = tf.random.uniform(
    [3,3],
    minval=0.05,
    maxval=0.1, #maxval if set to None then it defaults to 1
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(uniform_tensor)

tf.Tensor(
[[0.05392599 0.09943587 0.09393115]
 [0.09624134 0.0962387  0.06352568]
 [0.06629221 0.09186981 0.09268007]], shape=(3, 3), dtype=float32)


In [33]:
#seed argument

#A Python integer. Usedin combination with tf.random.set_seed to create a reproducible sequence of tensors across multiple calls

In [44]:
tf.random.set_seed(5) #when we use this we will have exact same output every time we run it

print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [50]:
tensor_indexed = tf.constant([1,2,3,4,5,6])
print(tensor_indexed)
print(tensor_indexed[0:4]) #here the last index is not included and the first index is included
print(tensor_indexed[2:6])

print(tensor_indexed[0:6:2]) #the last argument is the steps (skip by 2), by default it is 1
print(tensor_indexed[:6]) #all elements from 0 to 5
print(tensor_indexed[2:]) #all elemenst from the index 2 to 5 

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([3 4 5 6], shape=(4,), dtype=int32)


In [59]:
#indexing in 2d tensors

tensor_index_two_d = tf.constant([
    [1,2,3],
    [5,6,7],
    [4,2,4],
    [6,32,6]
])
#getting the first 3 rows and get the first 2 columns

print(tensor_index_two_d[0:3 , 0:2]) #the first argument is 0:3 that is go from 0th row to 2nd row , the second argument is for columns that is go from 0th column to 1st coulumn

#getting the first 3 rows and all the columns
print(tensor_index_two_d[0:3 ,:])
#getting just the 3rd row (2nd index)
print(tensor_index_two_d[2,:])

#getting the 2nd element in the row 4

print(tensor_index_two_d[3,1])

#getting the 0th column
print(tensor_index_two_d[:, 0])

#getting the first elements till the 3rd row
print(tensor_index_two_d[0:3, 0])

#get all the elements present in the 2nd row
print(tensor_index_two_d[:,1]) # or print(tensor_index_two_d[...,1])

tf.Tensor(
[[1 2]
 [5 6]
 [4 2]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [5 6 7]
 [4 2 4]], shape=(3, 3), dtype=int32)
tf.Tensor([4 2 4], shape=(3,), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor([1 5 4 6], shape=(4,), dtype=int32)
tf.Tensor([1 5 4], shape=(3,), dtype=int32)
tf.Tensor([ 2  6  2 32], shape=(4,), dtype=int32)


In [66]:
#indexing in 3d tensor

tensor_index_three_d = tf.constant([
    [
        [100,21,3],
        [23,62,7],
        [44,6,44],
        [6,32,61]
    ],
    [
        [18,2,3],
        [52,6,7],
        [45,2,4],
        [65,32,62]
    ],
    [
        [15,2,23],
        [467,246,7],
        [4,2,4],
        [66,32,6]
    ],
    [
        [12,27,30],
        [67,26,7],
        [45,462,467],
        [6,32,36]
    ]
])
#get the 3rd row of the 2nd matrix
print(tensor_index_three_d[1,2,:])
#get the first matrix
print(tensor_index_three_d[0,:,:])
#get the 2nd column of the 4th matrix
print(tensor_index_three_d[3,:,1])
#get the last column of the 2nd matrix
print(tensor_index_three_d[1,:,-1])

#get the last 2 matrices
print(tensor_index_three_d[2:4,:,:])

#get the last columns of the first 2 matrices
print(tensor_index_three_d[0:2,:,2])

tf.Tensor([45  2  4], shape=(3,), dtype=int32)
tf.Tensor(
[[100  21   3]
 [ 23  62   7]
 [ 44   6  44]
 [  6  32  61]], shape=(4, 3), dtype=int32)
tf.Tensor([ 27  26 462  32], shape=(4,), dtype=int32)
tf.Tensor([ 3  7  4 62], shape=(4,), dtype=int32)
tf.Tensor(
[[[ 15   2  23]
  [467 246   7]
  [  4   2   4]
  [ 66  32   6]]

 [[ 12  27  30]
  [ 67  26   7]
  [ 45 462 467]
  [  6  32  36]]], shape=(2, 4, 3), dtype=int32)
tf.Tensor(
[[ 3  7 44 61]
 [ 3  7  4 62]], shape=(2, 4), dtype=int32)


In [67]:
#math functions in tensorflow
#tf.math.abs computes the absolute value of a tensor

x_abs = tf.constant([-2.23,4.23,-100.45])
print(tf.math.abs(x_abs))

tf.Tensor([  2.23   4.23 100.45], shape=(3,), dtype=float32)


In [68]:
#finding the absoulute value of a complex tensor

x_complex = tf.constant(
    [
        [-2.25 +4.75j],
        [-323.23 +5.45j]
    ]
)

print(tf.math.abs(x_complex))

tf.Tensor(
[[  5.25594901]
 [323.27594312]], shape=(2, 1), dtype=float64)


In [78]:
tf.sqrt(16.) #it only accepts float32 values

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [87]:
x_1 = tf.constant([1,2,3,4], dtype=tf.int16)
x_2 = tf.constant([2,0,7,8], dtype=tf.int16)
x_3 = tf.constant([7], dtype=tf.int16)
#element by element wise operation
print(tf.add(x_1 , x_2))
print(tf.multiply(x_1 , x_2)) 
print(tf.subtract(x_1,x_2))
print(tf.divide(x_1, x_2))
print(tf.math.divide_no_nan(x_1, x_2)) #the output where it is inf or inifinity , by using this it will give you 0 instead of infinity
print(tf.add(x_1 , x_3)) #here 7 adds to all the elements in the array , this is broadcasting , here the smaller tensor is stretched out to match the shape of the bigger tensor so that the operation can be carried out


tf.Tensor([ 3  2 10 12], shape=(4,), dtype=int16)
tf.Tensor([ 2  0 21 32], shape=(4,), dtype=int16)
tf.Tensor([-1  2 -4 -4], shape=(4,), dtype=int16)
tf.Tensor([0.5               inf 0.42857143 0.5       ], shape=(4,), dtype=float32)
tf.Tensor([0.5        0.         0.42857143 0.5       ], shape=(4,), dtype=float32)
tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int16)


In [90]:
#matrix multiplication
m_1 = tf.constant([
    [1,2,3],
    [2,4,2],
    [2,4,1],
    [56,45,1]
])
print(m_1.shape)

m_2 = tf.constant([
    [1],
    [12],
    [12],
    [23]
])


print(m_2.shape)

m_res = tf.multiply(m_1, m_2)
print(m_res)

(4, 3)
(4, 1)
tf.Tensor(
[[   1    2    3]
 [  24   48   24]
 [  24   48   12]
 [1288 1035   23]], shape=(4, 3), dtype=int32)


In [93]:
#tf.math.maximum returns the maximum of 2 tensors , element wise
#tf.math.minimum returns the minimum of 2 tensors , element wise

print(tf.math.maximum(x_1 , x_2))
print(tf.math.minimum(x_1, x_2))

#it also supports the broadcast semantics for x_1 and x_2


tf.Tensor([2 2 7 8], shape=(4,), dtype=int16)
tf.Tensor([1 0 3 4], shape=(4,), dtype=int16)


In [95]:
#tf.math.argmax returns the index with the largest value across axes of a tensor
#tf.math.argmin returns the index with the smallest value across axes of a tensor
x_argmax = tf.constant([1,2,3,4,56,31])
print(tf.math.argmax(x_argmax))
print(tf.math.argmin(x_argmax))

tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [98]:
x_multidimensional = tf.constant([
    [23,453,213,456],
    [374,724,456,324],
    [345,6,35,67],
    [34,5467,12,453]
])

x_argmax_multi = tf.argmax(x_multidimensional , axis=0)
print(x_argmax_multi) 
#the output is [1,3,1,0] it means in column 1 the maximum element is in index 1 (here it is 374), in column 2 the largest element is in index 3 and so on

print(tf.argmax(x_multidimensional,axis=1)) #here we have specified the axis as 1 that means the array returned here [3,1,0,1] conveys that the maximum element present in row 1 is in index 3 (456) , in row 2 the maximum element is present in index 1 (724) ans so on

#same can be done for argmin

tf.Tensor([1 3 1 0], shape=(4,), dtype=int64)
tf.Tensor([3 1 0 1], shape=(4,), dtype=int64)


In [100]:
#tf.math.equal is the method used to compare two tensors , it returns a boolean tensor for element wise comparision results

x = tf.constant([2,4,3,5])
y = tf.constant([2,7,3,5])
z = tf.constant([2])

x_t_cmp = tf.math.equal(x,y)
print(x_t_cmp)
print(tf.math.equal(x,z)) #broadcasting

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)
tf.Tensor([ True False False False], shape=(4,), dtype=bool)


In [102]:
x = tf.constant([[2,4],[23,23]])
y = tf.constant([[3,1],[0,0]])
print(tf.math.pow(x,y))
tf.pow(tf.constant(4), tf.constant(2))

tf.Tensor(
[[8 4]
 [1 1]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=16>

In [122]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,15,6],
    [7,8,9]
], dtype=tf.float32)
 #summing the element present in the axis
print(tf.math.reduce_sum(tensor_two_d , axis=None , keepdims= False, name=None))
print(tf.math.reduce_sum(tensor_two_d , axis=0 , keepdims= False, name=None))
print(tf.math.reduce_sum(tensor_two_d , axis=1 , keepdims= False, name=None))
print(tf.math.reduce_sum(tensor_two_d , axis=1 , keepdims= True, name=None))
print(tf.math.reduce_sum(tensor_two_d , axis=0 , keepdims= False, name=None))

#getting the maximum element
print(tf.math.reduce_max(tensor_two_d , axis=None , keepdims= False, name=None))
print(tf.math.reduce_max(tensor_two_d , axis=1 , keepdims= True, name=None))
#similarly the min element 

#finding the mean value across the axis
print(tf.math.reduce_mean(tensor_two_d , axis=None , keepdims=False, name=None))
print(tf.math.reduce_mean(tensor_two_d , axis= 0 , keepdims=True, name=None))
print(tf.math.reduce_mean(tensor_two_d , axis=1 , keepdims=True, name=None))

#similarly we have standard deviation , reduce_any etc ->tensorflow documentation

tf.Tensor(55.0, shape=(), dtype=float32)
tf.Tensor([12. 25. 18.], shape=(3,), dtype=float32)
tf.Tensor([ 6. 25. 24.], shape=(3,), dtype=float32)
tf.Tensor(
[[ 6.]
 [25.]
 [24.]], shape=(3, 1), dtype=float32)
tf.Tensor([12. 25. 18.], shape=(3,), dtype=float32)
tf.Tensor(15.0, shape=(), dtype=float32)
tf.Tensor(
[[ 3.]
 [15.]
 [ 9.]], shape=(3, 1), dtype=float32)
tf.Tensor(6.111111, shape=(), dtype=float32)
tf.Tensor([[4.       8.333333 6.      ]], shape=(1, 3), dtype=float32)
tf.Tensor(
[[2.      ]
 [8.333333]
 [8.      ]], shape=(3, 1), dtype=float32)


In [127]:
#the top values 
tf.math.top_k(tensor_two_d, k=2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 3.,  2.],
       [15.,  6.],
       [ 9.,  8.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 2],
       [2, 1]])>)

In [128]:
#LINEAR ALGEBRA OPERATIONS
#tf.linalg.matmul 
#this is actual matrix multiplication (row by column) 
#multiplies matrix a by matrix b producing a*b

mat_1 = tf.constant([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

mat_2 = tf.constant([
    [4,5],
    [4,8],
    [3,0]
])

product_mat = tf.linalg.matmul(
    mat_1, mat_2 , transpose_a=False , transpose_b=False , adjoint_a=False , adjoint_b=False, a_is_sparse= False , b_is_sparse=False , output_type=None , name = None
)
print(product_mat)

tf.Tensor(
[[21 21]
 [32 34]
 [43 47]], shape=(3, 2), dtype=int32)


In [129]:
#another way of multiplying two matrices

print(mat_1 @ mat_2)

tf.Tensor(
[[21 21]
 [32 34]
 [43 47]], shape=(3, 2), dtype=int32)


In [131]:
#transpose of a matrix
tf.transpose(mat_1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])>

In [134]:
#in case of 3d matrices
x_1 = tf.constant([
    [
        [12,32,43],
        [12,32,43],
        [12,32,43]
    ],
    [
        [12,32,43],
        [12,32,43],
        [12,32,43]
    ],
    [
        [12,32,43],
        [12,32,43],
        [12,32,43]
    ]
])

x_2 = tf.constant([
        [
            [12,32,43],
            [12,32,43],
            [12,32,43]
        ],
        [
            [12,32,43],
            [12,32,43],
            [12,32,43]
        ],
        [
            [12,32,43],
            [12,32,43],
            [12,32,43]
        ]
    
    ])
print(x_1 @ x_2)

tf.Tensor(
[[[1044 2784 3741]
  [1044 2784 3741]
  [1044 2784 3741]]

 [[1044 2784 3741]
  [1044 2784 3741]
  [1044 2784 3741]]

 [[1044 2784 3741]
  [1044 2784 3741]
  [1044 2784 3741]]], shape=(3, 3, 3), dtype=int32)


In [135]:
#optimising calculation for tensors which are mostly zeros : -- sparse tensors

In [138]:
#function to find the inverse of a tensor (a matrix)

tensor_two_d = tf.constant([
    [1,2,3],
    [1,6,7],
    [5,5,7]
], dtype=tf.float32)

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)
print(tensor_two_d_inv)

tf.Tensor(
[[-0.58333343 -0.0833334   0.33333334]
 [-2.3333333   0.6666667   0.3333333 ]
 [ 2.0833333  -0.41666666 -0.3333333 ]], shape=(3, 3), dtype=float32)


In [139]:
#mutipying the matrix with its inverse , results in a indentity matrix

print(tensor_two_d_inv @ tensor_two_d)

tf.Tensor(
[[ 9.9999988e-01 -5.0663948e-07 -5.6624413e-07]
 [ 5.9604645e-08  1.0000002e+00 -5.9604645e-08]
 [ 5.9604645e-08 -5.9604645e-08  1.0000002e+00]], shape=(3, 3), dtype=float32)


In [140]:
s,u,v = tf.linalg.svd(tensor_two_d) 

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([13.806951  ,  2.8769662 ,  0.30209848], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.2699263 , -0.05626307, -0.9612356 ],
        [ 0.6546088 , -0.7213813 ,  0.22604561],
        [ 0.7061355 ,  0.6902489 ,  0.15788949]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.322679  ,  0.9293122 ,  0.17960182],
        [ 0.5792868 , -0.3439628 ,  0.73899686],
        [ 0.7485352 , -0.13441783, -0.64932793]], dtype=float32)>)

In [141]:
#numpy matrix operation

import numpy as np 

In [142]:
A = np.array([
    [1,2,3],
    [1,4,6],
    [3,5,3]
])

B = np.array([
    [5,7,3],
    [3,2,5],
    [234,21,1]
])

C = np.matmul(A,B)
print(C)

[[ 713   74   16]
 [1421  141   29]
 [ 732   94   37]]


In [144]:
print("Eninsum C =: \n")
print(np.einsum("ij,jk -> ik", A,B))

Eninsum C =: 

[[ 713   74   16]
 [1421  141   29]
 [ 732   94   37]]


In [147]:
#for element wise multiplication

print(A.shape)
print(B.shape)
#the shape of the matrices must be same for element wise multiplication

print("Hardamond C =: \n")
print(A*B)

print("Enisum C =: \n")
print(np.einsum ('ij, ij -> ij', A,B))



(3, 3)
(3, 3)
Hardamond C =: 

[[  5  14   9]
 [  3   8  30]
 [702 105   3]]
Enisum C =: 

[[  5  14   9]
 [  3   8  30]
 [702 105   3]]


In [149]:
#transpose of a matrix

print(A)
print("The transpose of the matrix is :")
print("Einsum Transpose A =: \n")
print(np.einsum("ij -> ji", A))

[[1 2 3]
 [1 4 6]
 [3 5 3]]
The transpose of the matrix is :
Einsum Transpose A =: 

[[1 1 3]
 [2 4 5]
 [3 6 3]]


In [151]:
#multiplying 3D arrays

A = np.array([
    [
        [1,2,3],
        [1,2,3],
        [1,2,3]
    ],
    [
        [1,2,3],
        [1,2,3],
        [1,2,3]
    ],
    [
        [1,2,3],
        [1,2,3],
        [1,2,3]
    ],
    
])
B = np.array([
    [
        [1,2,3],
        [1,2,3],
        [1,2,3]
    ],
    [
        [1,2,3],
        [1,2,3],
        [1,2,3]
    ],
    [
        [1,2,3],
        [1,2,3],
        [1,2,3]
    ],
    
])

print(A.shape)
print("Batch multiplication C =: \n")
print(np.matmul(A,B), "\n")

print("Einsum C =: \n")
print(np.einsum('bij, bjk -> bik', A,B))

(3, 3, 3)
Batch multiplication C =: 

[[[ 6 12 18]
  [ 6 12 18]
  [ 6 12 18]]

 [[ 6 12 18]
  [ 6 12 18]
  [ 6 12 18]]

 [[ 6 12 18]
  [ 6 12 18]
  [ 6 12 18]]] 

Einsum C =: 

[[[ 6 12 18]
  [ 6 12 18]
  [ 6 12 18]]

 [[ 6 12 18]
  [ 6 12 18]
  [ 6 12 18]]

 [[ 6 12 18]
  [ 6 12 18]
  [ 6 12 18]]]


In [152]:
#finding the sum of all the elements in an array

print(np.sum(A))

54


In [153]:
print("Einsum A =: \n")
print(np.einsum('bij ->', A))

Einsum A =: 

54


In [156]:
# print("Axis 0 sum A =: \n")
# print(np.sum(A,axis=0))

# print("Einsum A =: \n")
# print(np.einsum('ij -> j', A))

# print("Axis 1 sum A =: \n")
# print(np.sum(A , axis=1),"\n")

# print("Einsum A =: \n")
# print(np.einsum('ij -> i', A))

In [159]:
A = np.random.randn(2,4,4,2) #bcij
B = np.random.randn(2,4,4,1) #bcik

np.einsum("bcik, bcij -> bckj", B,A)

array([[[[ 0.62897486,  1.30340573]],

        [[-1.02072197, -1.33402744]],

        [[-0.93871187,  0.56151815]],

        [[ 0.34243805, -2.05412001]]],


       [[[ 2.83401394,  1.07017   ]],

        [[ 4.82793318, -1.48811041]],

        [[ 0.27282957, -0.21933503]],

        [[-0.22646206, -0.7592533 ]]]])

In [160]:
#tf.expand_dims -> adds an extra axis to the tensor

tensor_three_d.shape

TensorShape([2, 4, 3])

In [163]:
#change the shape of the above matrix to 1,2,4,3
add_dims_tensor_three_d = tf.expand_dims(tensor_three_d, axis=0)
print(add_dims_tensor_three_d.shape)
print("the original matrix: ",tensor_three_d)
print("After adding an extra dimension to the matrix", add_dims_tensor_three_d)

(1, 2, 4, 3)
the original matrix:  tf.Tensor(
[[[  1   4   3]
  [  1   5 454]
  [ 34 565 424]
  [123 453  67]]

 [[  1   4   3]
  [  1   5 454]
  [ 34 565 424]
  [123 453  67]]], shape=(2, 4, 3), dtype=int32)
After adding an extra dimension to the matrix tf.Tensor(
[[[[  1   4   3]
   [  1   5 454]
   [ 34 565 424]
   [123 453  67]]

  [[  1   4   3]
   [  1   5 454]
   [ 34 565 424]
   [123 453  67]]]], shape=(1, 2, 4, 3), dtype=int32)


In [164]:
#tf.squeez method removes dimension of size 1 from the shape of the tensor

print(tf.squeeze(add_dims_tensor_three_d).shape)

(2, 4, 3)


In [168]:
print(tf.squeeze(add_dims_tensor_three_d , axis=0))

tf.Tensor(
[[[  1   4   3]
  [  1   5 454]
  [ 34 565 424]
  [123 453  67]]

 [[  1   4   3]
  [  1   5 454]
  [ 34 565 424]
  [123 453  67]]], shape=(2, 4, 3), dtype=int32)


In [169]:
print(tf.reshape(add_dims_tensor_three_d, [6,4]))

tf.Tensor(
[[  1   4   3   1]
 [  5 454  34 565]
 [424 123 453  67]
 [  1   4   3   1]
 [  5 454  34 565]
 [424 123 453  67]], shape=(6, 4), dtype=int32)


In [170]:
print(tf.reshape(add_dims_tensor_three_d, [24]))

tf.Tensor(
[  1   4   3   1   5 454  34 565 424 123 453  67   1   4   3   1   5 454
  34 565 424 123 453  67], shape=(24,), dtype=int32)


In [171]:
#if we donot know the dimension while reshaping the tensor , then we can give a -1 to the arguments , tensorflow will calculate the other dimension of the reshaped tensor

print(tf.reshape(add_dims_tensor_three_d, [8,-1]))

tf.Tensor(
[[  1   4   3]
 [  1   5 454]
 [ 34 565 424]
 [123 453  67]
 [  1   4   3]
 [  1   5 454]
 [ 34 565 424]
 [123 453  67]], shape=(8, 3), dtype=int32)


In [178]:
#concating two matrices

t1 = np.array([
    [1,2,3],
    [3,4,5]
])

t2 = np.array([
    [1,2,3],
    [15,6,4]
])

print(t1.shape)
print(t2.shape)

print(tf.concat([t1,t2], axis=1)) #axis 0 means concatination accross column , and axis = 1 means concating across row

(2, 3)
(2, 3)
tf.Tensor(
[[ 1  2  3  1  2  3]
 [ 3  4  5 15  6  4]], shape=(2, 6), dtype=int32)


In [185]:
#in tensorflow : if we stack two matrices and specify the axis , then we create a new axis at that position

#if axis = 0 , then we create a axis at the position 0
print(t1)
print(t2)

print(tf.stack([t1, t2], axis=2))

[[1 2 3]
 [3 4 5]]
[[ 1  2  3]
 [15  6  4]]
tf.Tensor(
[[[ 1  1]
  [ 2  2]
  [ 3  3]]

 [[ 3 15]
  [ 4  6]
  [ 5  4]]], shape=(2, 3, 2), dtype=int32)
