In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4) #creates a tensor 0 dimensional tensor

In [3]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([1.0,2,-4])
print(tensor_one_d)

tf.Tensor([ 1.  2. -4.], shape=(3,), dtype=float32)


In [8]:
tensor_two_d  = tf.constant([
    [2,5,-1],
    [2,4,1],
    [3,123,5],
    [3,8,9]
])

In [9]:
print(tensor_two_d)

tf.Tensor(
[[  2   5  -1]
 [  2   4   1]
 [  3 123   5]
 [  3   8   9]], shape=(4, 3), dtype=int32)


In [10]:
tensor_three_d = tf.constant([
    [
        [1,4,3],
        [1,5,454],
        [34,565,424],
        [123,453,67]
    ],
    [
        [1,4,3],
        [1,5,454],
        [34,565,424],
        [123,453,67]
    ]
    
])

print(tensor_three_d)

tf.Tensor(
[[[  1   4   3]
  [  1   5 454]
  [ 34 565 424]
  [123 453  67]]

 [[  1   4   3]
  [  1   5 454]
  [ 34 565 424]
  [123 453  67]]], shape=(2, 4, 3), dtype=int32)


In [11]:
print(tensor_three_d.shape)

(2, 4, 3)


In [13]:
print(tensor_three_d.ndim) # 3 d tensor

3


In [16]:
tensor_four_d = tf.constant([
    [
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,3,4,65],
            [34,5,4,657,324]
        ],
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,3,4,65],
            [34,54,65,7,324]
        ],
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [2,3,6,34,65],
            [34,54,6,57,324]
        ],
    ],
     [
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,3,4,65],
            [34,54,657,3,24]
        ],
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,34,6,5],
            [34,54,657,3,24]
        ],
        [
            [1,2,3,4,5],
            [4,2,7,2,6],
            [23,6,34,65,4],
            [34,54,657,2,324]
        ]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6   3   4  65]
   [ 34   5   4 657 324]]

  [[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6   3   4  65]
   [ 34  54  65   7 324]]

  [[  1   2   3   4   5]
   [  4   2   7   2   6]
   [  2   3   6  34  65]
   [ 34  54   6  57 324]]]


 [[[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6   3   4  65]
   [ 34  54 657   3  24]]

  [[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6  34   6   5]
   [ 34  54 657   3  24]]

  [[  1   2   3   4   5]
   [  4   2   7   2   6]
   [ 23   6  34  65   4]
   [ 34  54 657   2 324]]]], shape=(2, 3, 4, 5), dtype=int32)


In [19]:
tensor_one_d_32 = tf.constant([23,4,5,1], dtype=tf.float32) #pecision value is 32, if it is float16 then less memory is required to store it

In [20]:
print(tensor_one_d_32)

tf.Tensor([23.  4.  5.  1.], shape=(4,), dtype=float32)


In [23]:
casted_tensor_one_d = tf.cast(tensor_one_d , dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [24]:
tensor_bool = tf.constant([True, True, False, True])
print(tensor_bool)

tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


In [25]:
cast_tensor_bool = tf.cast(tensor_bool , dtype=tf.int16)
print(cast_tensor_bool)

tf.Tensor([1 1 0 1], shape=(4,), dtype=int16)


In [26]:
tensor_string = tf.constant("Hello world")
print(tensor_string)

tf.Tensor(b'Hello world', shape=(), dtype=string)


In [28]:
#creating a four dimensional tensor of type string with dimension 2*2*3*1

tensor_string_four_d = tf.constant([
    [
        [
           ["hello World"],
           ["hello World"],
           ["hello World"] 
        ],
        [
            ["hello World"],
            ["hello World"],
            ["hello World"]
        ]
    ],
    [
         [
            ["hello World"],
            ["hello World"],
            ["hello World"]
         ],
         [
            ["hello World"],
            ["hello World"],
            ["hello World"]
         ]
    ]
])
print(tensor_string_four_d)

tf.Tensor(
[[[[b'hello World']
   [b'hello World']
   [b'hello World']]

  [[b'hello World']
   [b'hello World']
   [b'hello World']]]


 [[[b'hello World']
   [b'hello World']
   [b'hello World']]

  [[b'hello World']
   [b'hello World']
   [b'hello World']]]], shape=(2, 2, 3, 1), dtype=string)


In [29]:
import numpy as np 


In [30]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [31]:
print(np_array.shape)

(3,)


In [32]:
#converting the numpy array into tensor
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [46]:
#identity matrix

eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None, #when we define the number of columns as n then the number of columns automatically takes in the value of n
    batch_shape=[2,2], #batch size determines the dimensions of the matrices if batch_shape = [2,] that is we want 2 5*5 identity matrices
    dtype=tf.dtypes.float64,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 2, 5, 5), dtype=float64)


In [50]:
#the fill method creates a tensor filled with a scalar value
tensor_nine = tf.fill([2,3,5,5],9)
print(tensor_nine)

tf.Tensor(
[[[[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]

  [[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]

  [[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]]


 [[[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]

  [[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]

  [[9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]
   [9 9 9 9 9]]]], shape=(2, 3, 5, 5), dtype=int32)


In [51]:
#tf.ones() mehod creates a tensor with all elements set to one

tensor_one = tf.ones(
    shape=[2,2],
    dtype=tf.float16,
    name=None
)

print(tensor_one)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float16)


In [53]:
#the method tf.ones_like() : - creates a tensor of all ones that has the same shape as the input

#it will create the same array (same dimension) as the input array that is passed to it with all its values set to 1

ones_like_tensor = tf.ones_like(
    tensor_nine , dtype=tf.int16 , name=None
)

print(ones_like_tensor)



tf.Tensor(
[[[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]


 [[[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]]], shape=(2, 3, 5, 5), dtype=int16)


In [54]:
#tf.zeros method creates a tensor with all elements set to zero

zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.float32,
    name=None
)

print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [56]:
print(tf.shape(tensor_three_d)) #prints the shape of the tensor tensor_three_d as a list

tf.Tensor([2 4 3], shape=(3,), dtype=int32)


In [57]:
#the rank method returns the rank of a tensor

rank_two_d_tensor = tf.rank(
    tensor_two_d , name=None
)

print(rank_two_d_tensor)

tf.Tensor(2, shape=(), dtype=int32)


In [59]:
#the size method returns the size of a tensor

size_of_three_d_tensor = tf.size(
    tensor_three_d,
    out_type=tf.dtypes.int16,
    name=None
)
print(tensor_three_d.shape)
print(size_of_three_d_tensor)

(2, 4, 3)
tf.Tensor(24, shape=(), dtype=int16)


In [66]:
random_tensor = tf.random.normal(
    [3,2],
    mean=2.0,
    stddev=1.9,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)



tf.Tensor(
[[-0.42658973 -0.8599255 ]
 [ 4.6454186   5.117605  ]
 [ 5.325585   -0.28440356]], shape=(3, 2), dtype=float32)


In [69]:
#generating random normals from uniform distribution

#tf.random.uniform : outputs random values from a uniform distribution

uniform_tensor = tf.random.uniform(
    [3,3],
    minval=0,
    maxval=0.1, #maxval if set to None then it defaults to 1
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(uniform_tensor)

tf.Tensor(
[[0.06950327 0.06205171 0.03137449]
 [0.0056103  0.09176873 0.01837716]
 [0.09484754 0.02956945 0.0583853 ]], shape=(3, 3), dtype=float32)


In [70]:
#seed argument

#A Python integer. Usedin combination with tf.random.set_seed to create a reproducible sequence of tensors across multiple calls